version: 0.0.{build}
# branches:
#   only:
#     - master
#build: Script
# todo: matrix for each deployment style (localPS, remotePS, Ansible, etc)
build: off
only_commits:
  files:
    - CovidLabLocal.ps1
    - CovidLabRemote.ps1
    - config.xml
    - appveyor.yml
max_jobs: 1
platform: Any CPU
#  - x86
#  - Any CPU
#  - X64
before_test:
  - echo script1
  - ps: Write-Host "script1"
test_script:
  - echo This is my custom test script
after_test:
# before_deploy:
#   - ps:
artifacts:
  - path: CovidLabLocal.ps1
  - path: CovidLabRemote.ps1
  - path: config.xml
after_deploy:
  - provider: GitHub
    artifact: scripts/
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
